[package]
name = "rust-bokeh"
version = "0.1.0"
authors = ["Simon Walker <s.r.walker101@googlemail.com>"]

[dependencies]
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.33"
askama = "0.7.2"

[build-dependencies]
askama = "0.7.2"
